name: tradingsystem
region: nyc
services:
  - name: dashboard
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: streamlit run src/dashboard/streamlit_app.py --server.port 8080 --server.address 0.0.0.0 --server.headless true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      path: /_stcore/health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL

  - name: web
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: python -m src.health
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL

  - name: worker
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: python -m src.main
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL
