name: tradingsystem
region: nyc
services:
  - name: web
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: python -m src.health
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL

  - name: worker
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: python migrate_schema.py && python run.py live --force --with-health
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: KRAKEN_FUTURES_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL
      - key: USE_STATE_MACHINE_V2
        value: "true"
        scope: RUN_TIME
        type: GENERAL
      - key: DRY_RUN
        value: "0"
        scope: RUN_TIME
        type: GENERAL
      - key: SYSTEM_DRY_RUN
        value: "false"
        scope: RUN_TIME
        type: GENERAL
      - key: TRADING_NEW_ENTRIES_ENABLED
        value: "true"
        scope: RUN_TIME
        type: GENERAL
      - key: TRADING_REVERSALS_ENABLED
        value: "true"
        scope: RUN_TIME
        type: GENERAL
      - key: TRADING_PARTIALS_ENABLED
        value: "true"
        scope: RUN_TIME
        type: GENERAL
      - key: TRADING_TRAILING_ENABLED
        value: "true"
        scope: RUN_TIME
        type: GENERAL

  - name: dashboard
    github:
      repo: ArielB1980/TradingSystem
      branch: main
    run_command: streamlit run src/dashboard/streamlit_app.py --server.port 8080 --server.address 0.0.0.0 --server.headless true
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /dashboard
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        value: prod
        scope: RUN_TIME
        type: GENERAL
